# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scripts/main_window.ui'
#
# Created: Sun Nov 18 16:42:17 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.descriptionLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.descriptionLineEdit.setObjectName("descriptionLineEdit")
        self.horizontalLayout_2.addWidget(self.descriptionLineEdit)
        self.recordButton = QtGui.QPushButton(self.centralwidget)
        self.recordButton.setEnabled(False)
        self.recordButton.setMaximumSize(QtCore.QSize(853, 16777215))
        self.recordButton.setCheckable(True)
        self.recordButton.setObjectName("recordButton")
        self.horizontalLayout_2.addWidget(self.recordButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tableView = QtGui.QTableView(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_2.addWidget(self.tableView)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setMaximumSize(QtCore.QSize(20, 100))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.xStdDevLcd = QtGui.QLCDNumber(self.centralwidget)
        self.xStdDevLcd.setMinimumSize(QtCore.QSize(0, 30))
        self.xStdDevLcd.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.xStdDevLcd.setFont(font)
        self.xStdDevLcd.setObjectName("xStdDevLcd")
        self.horizontalLayout_5.addWidget(self.xStdDevLcd)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(20, 100))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.yStdDevLcd = QtGui.QLCDNumber(self.centralwidget)
        self.yStdDevLcd.setMinimumSize(QtCore.QSize(0, 30))
        self.yStdDevLcd.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.yStdDevLcd.setFont(font)
        self.yStdDevLcd.setObjectName("yStdDevLcd")
        self.horizontalLayout_5.addWidget(self.yStdDevLcd)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setMaximumSize(QtCore.QSize(20, 100))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.zStdDevLcd = QtGui.QLCDNumber(self.centralwidget)
        self.zStdDevLcd.setMinimumSize(QtCore.QSize(0, 30))
        self.zStdDevLcd.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.zStdDevLcd.setFont(font)
        self.zStdDevLcd.setObjectName("zStdDevLcd")
        self.horizontalLayout_5.addWidget(self.zStdDevLcd)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setMaximumSize(QtCore.QSize(20, 100))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.xVarianceLcd = QtGui.QLCDNumber(self.centralwidget)
        self.xVarianceLcd.setMinimumSize(QtCore.QSize(0, 30))
        self.xVarianceLcd.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.xVarianceLcd.setFont(font)
        self.xVarianceLcd.setObjectName("xVarianceLcd")
        self.horizontalLayout_6.addWidget(self.xVarianceLcd)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setMaximumSize(QtCore.QSize(20, 100))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.yVarianceLcd = QtGui.QLCDNumber(self.centralwidget)
        self.yVarianceLcd.setMinimumSize(QtCore.QSize(0, 30))
        self.yVarianceLcd.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.yVarianceLcd.setFont(font)
        self.yVarianceLcd.setObjectName("yVarianceLcd")
        self.horizontalLayout_6.addWidget(self.yVarianceLcd)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setMaximumSize(QtCore.QSize(20, 100))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.zVarianceLcd = QtGui.QLCDNumber(self.centralwidget)
        self.zVarianceLcd.setMinimumSize(QtCore.QSize(0, 30))
        self.zVarianceLcd.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.zVarianceLcd.setFont(font)
        self.zVarianceLcd.setObjectName("zVarianceLcd")
        self.horizontalLayout_6.addWidget(self.zVarianceLcd)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuPoints = QtGui.QMenu(self.menubar)
        self.menuPoints.setObjectName("menuPoints")
        self.menuStream = QtGui.QMenu(self.menubar)
        self.menuStream.setObjectName("menuStream")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen_Log = QtGui.QAction(MainWindow)
        self.actionOpen_Log.setObjectName("actionOpen_Log")
        self.actionWrite = QtGui.QAction(MainWindow)
        self.actionWrite.setObjectName("actionWrite")
        self.actionClear_All = QtGui.QAction(MainWindow)
        self.actionClear_All.setObjectName("actionClear_All")
        self.actionManual_Entry = QtGui.QAction(MainWindow)
        self.actionManual_Entry.setObjectName("actionManual_Entry")
        self.actionConnect_to_MOOSDB = QtGui.QAction(MainWindow)
        self.actionConnect_to_MOOSDB.setObjectName("actionConnect_to_MOOSDB")
        self.actionRun_pAntler = QtGui.QAction(MainWindow)
        self.actionRun_pAntler.setObjectName("actionRun_pAntler")
        self.actionUMS = QtGui.QAction(MainWindow)
        self.actionUMS.setObjectName("actionUMS")
        self.menuFile.addAction(self.actionWrite)
        self.menuFile.addAction(self.actionExit)
        self.menuPoints.addAction(self.actionClear_All)
        self.menuPoints.addAction(self.actionManual_Entry)
        self.menuStream.addAction(self.actionConnect_to_MOOSDB)
        self.menuStream.addAction(self.actionRun_pAntler)
        self.menuStream.addAction(self.actionUMS)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuStream.menuAction())
        self.menubar.addAction(self.menuPoints.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "GAVLab RTK Survey", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Point Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.recordButton.setText(QtGui.QApplication.translate("MainWindow", "Record Point", None, QtGui.QApplication.UnicodeUTF8))
        self.recordButton.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Std Dev:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Z:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Variance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Z:", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPoints.setTitle(QtGui.QApplication.translate("MainWindow", "Points", None, QtGui.QApplication.UnicodeUTF8))
        self.menuStream.setTitle(QtGui.QApplication.translate("MainWindow", "Stream", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Log.setText(QtGui.QApplication.translate("MainWindow", "Open Log...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Log.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWrite.setText(QtGui.QApplication.translate("MainWindow", "Write...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWrite.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_All.setText(QtGui.QApplication.translate("MainWindow", "Clear All...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionManual_Entry.setText(QtGui.QApplication.translate("MainWindow", "Manual Entry...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionManual_Entry.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+M", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect_to_MOOSDB.setText(QtGui.QApplication.translate("MainWindow", "Connect to MOOSDB...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_pAntler.setText(QtGui.QApplication.translate("MainWindow", "Run pAntler...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUMS.setText(QtGui.QApplication.translate("MainWindow", "uMS...", None, QtGui.QApplication.UnicodeUTF8))

